# Generated by Django 3.1.3 on 2020-11-16 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
