# Generated by Django 3.1.3 on 2020-11-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0002_auto_20201116_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user.svg', null=True, upload_to='hod'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user.svg', null=True, upload_to='student'),
        ),
    ]
